version: "3"
services:
  react-app:
    image: frontend
    stdin_open: true
    ports: 
      - "3000:3000"
  api-server:
    image: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_URI: "mongodb+srv://abhay:banerjee@dev-cluster.jbmkpl0.mongodb.net/news-prograd"


